# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vv3chopTuF98GaC4tcX8R51HQkJukeH

# Lab 4: RNN vs LSTM vs GRU Comparison on IMDB Dataset

### Objective:
Compare the performance of Simple RNN, LSTM, and GRU models on the IMDB movie review sentiment classification dataset, focusing on accuracy, loss, and training time.
"""

import numpy as np
import matplotlib.pyplot as plt
import time

from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense

"""## 1. Data Loading and Preprocessing

We will load the IMDB dataset, which consists of movie reviews labeled as positive (1) or negative (0). Each review is represented as a sequence of integers, where each integer denotes a specific word in the vocabulary. We'll preprocess the data by padding sequences to a fixed length.
"""

# Parameters for data loading and preprocessing
max_words = 10000  # Vocabulary size (take only the top `max_words` most frequent words)
maxlen = 100       # Sequence length (pad/truncate reviews to this length)
embedding_dim = 64 # Dimension of the word embeddings

# Load the IMDB dataset
print(f"Loading IMDB dataset with {max_words} most frequent words...")
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_words)
print(f"Train sequences: {len(x_train)}, Test sequences: {len(x_test)}")

# Pad sequences to a fixed length
print(f"Padding sequences to length {maxlen}...")
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test = pad_sequences(x_test, maxlen=maxlen)
print(f"x_train shape: {x_train.shape}, y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}, y_test shape: {y_test.shape}")

"""## 2. Model Building

We will build three different models: Simple RNN, LSTM, and GRU. Each model will start with an `Embedding` layer to convert word indices into dense vectors, followed by the respective recurrent layer, and finally a `Dense` layer with a sigmoid activation for binary classification.
"""

def build_model(model_type, vocab_size, embedding_dim, input_length):
    model = Sequential()
    # Embedding layer to convert word indices to dense vectors
    model.add(Embedding(vocab_size, embedding_dim, input_length=input_length))

    if model_type == "RNN":
        # SimpleRNN layer: often struggles with long-range dependencies
        model.add(SimpleRNN(32)) # 32 units
    elif model_type == "LSTM":
        # LSTM layer: designed to handle vanishing gradient problem and long-term dependencies
        model.add(LSTM(32))
    elif model_type == "GRU":
        # GRU layer: a simplified version of LSTM with fewer parameters
        model.add(GRU(32))
    else:
        raise ValueError("model_type must be 'RNN', 'LSTM', or 'GRU'")

    # Output layer for binary classification (sentiment: positive/negative)
    model.add(Dense(1, activation='sigmoid'))

    # Compile the model
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    return model

print("Model building function defined.")

"""## 3. Training and Evaluation

We will train each model for a few epochs and record their training time, loss, and accuracy on the test set. For demonstration purposes, we'll use 5 epochs, but more epochs might be needed for optimal performance.
"""

models = {}
histories = {}
training_times = {}

model_types = ["RNN", "LSTM", "GRU"]
epochs = 5 # Reduced epochs for a quicker demonstration
batch_size = 32

for model_type in model_types:
    print(f"\n--- Training {model_type} Model ---")
    model = build_model(model_type, max_words, embedding_dim, maxlen)
    model.summary()

    start_time = time.time()
    history = model.fit(x_train, y_train,
                                epochs=epochs,
                                batch_size=batch_size,
                                validation_split=0.2, # Use 20% of training data for validation
                                verbose=1) # Show training progress
    end_time = time.time()
    training_time = end_time - start_time

    loss, accuracy = model.evaluate(x_test, y_test, verbose=0) # Evaluate silently

    models[model_type] = model
    histories[model_type] = history
    training_times[model_type] = training_time

    print(f"\n{model_type} Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")
    print(f"{model_type} Training Time: {training_time:.2f} seconds")

"""## 4. Comparison and Visualization

Here, we visualize the training and validation accuracy and loss for each model across epochs. We will also display a summary table comparing their test accuracy and training times.
"""

plt.figure(figsize=(15, 6))

# Plot training & validation accuracy values
plt.subplot(1, 2, 1)
for model_type in model_types:
    plt.plot(histories[model_type].history['accuracy'], label=f'{model_type} Train Acc')
    plt.plot(histories[model_type].history['val_accuracy'], label=f'{model_type} Val Acc', linestyle='--')
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(loc='lower right')
plt.grid(True)

# Plot training & validation loss values
plt.subplot(1, 2, 2)
for model_type in model_types:
    plt.plot(histories[model_type].history['loss'], label=f'{model_type} Train Loss')
    plt.plot(histories[model_type].history['val_loss'], label=f'{model_type} Val Loss', linestyle='--')
plt.title('Model Loss Comparison')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(loc='upper right')
plt.grid(True)

plt.tight_layout()
plt.show()

import pandas as pd

results = []
for model_type in model_types:
    # Evaluate on test set to get final accuracy and loss
    loss, accuracy = models[model_type].evaluate(x_test, y_test, verbose=0)
    results.append({
        'Model': model_type,
        'Test Loss': f"{loss:.4f}",
        'Test Accuracy': f"{accuracy:.4f}",
        'Training Time (s)': f"{training_times[model_type]:.2f}"
    })

results_df = pd.DataFrame(results)
print("\n--- Model Comparison Summary ---")
display(results_df)