# -*- coding: utf-8 -*-
"""lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdLFJGVXchJ5Xv3S7-FmWCwxYGB0HupV

## Lab 5: LSTM Text Classification with Seq2Seq

### 1. Problem Statement
Build an LSTM model to classify text into categories (e.g., positive vs negative sentiment).

### 2. Dataset (Recommended)
Use:
* IMDB Dataset (built into TensorFlow)
* Binary classification: Positive / Negative reviews

### 3. Step-by-Step Implementation

#### 🔹 Step 1: Import Libraries
"""

import numpy as np
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

"""#### 🔹 Step 2: Load Dataset"""

vocab_size = 10000  # top 10k words

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=vocab_size)

"""#### 🔹 Step 3: Preprocessing (Padding)
👉 This ensures all sequences have equal length.
"""

max_len = 200  # max words per review

X_train = pad_sequences(X_train, maxlen=max_len)
X_test = pad_sequences(X_test, maxlen=max_len)

"""#### 🔹 Step 4: Build LSTM Model"""

model = Sequential()

# Convert words into dense vectors
model.add(Embedding(input_dim=vocab_size, output_dim=128, input_length=max_len))

# LSTM layer
model.add(LSTM(64))

# Output layer
model.add(Dense(1, activation='sigmoid'))

model.summary()

"""#### 🔹 Step 5: Compile Model"""

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

"""#### 🔹 Step 6: Train Model"""

history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

"""#### 🔹 Step 6: Train Model (Continued)

Re-running the training as it was interrupted.
"""

history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

"""#### 🔹 Step 7: Evaluate Model (Continued)"""

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

"""### 5. Plot Graphs (Continued)"""

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])
plt.show()

"""#### 🔹 Step 7: Evaluate Model"""

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

"""### 4. Expected Output
* Accuracy: ~85% – 88%
* Training time: Moderate
* Better than simple RNN

### 5. Plot Graphs
"""

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])
plt.show()

"""### 6. Explanation
* Embedding Layer: Converts words into vectors
* LSTM Layer: Captures sequence dependencies
* Sigmoid Output: Binary classification

### 7. Why LSTM Works Better?
* Remembers long-term dependencies
* Avoids vanishing gradient problem
* Captures context in sentences

### 8. Final Conclusion
The LSTM model effectively captures sequential dependencies in text data, leading to improved classification performance compared to traditional neural networks. It is well-suited for natural language processing tasks such as sentiment analysis.

### Improvements (For Extra Marks)
Try adding:

`model.add(LSTM(64, dropout=0.2, recurrent_dropout=0.2))`

OR stack layers:

`model.add(LSTM(64, return_sequences=True))`
`model.add(LSTM(32))`
"""