# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ycyx3uelHObBap_m6VgwIxohrAyFxirD

# Lab 6: Attention Heatmap Visualization
🎯 **Objective**

To visualize how a model focuses on different words using the Attention Mechanism.

________________________________________
⚙️ **Methodology**

*   Take a sample sentence
*   Assign attention weights
*   Normalize using softmax
*   Plot heatmap
"""

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns

sentence = ["I", "love", "deep", "learning"]
attention_weights = torch.tensor([0.1, 0.3, 0.4, 0.2])

attention_weights = F.softmax(attention_weights, dim=0).detach().numpy()

sns.heatmap([attention_weights], annot=True, xticklabels=sentence, cmap="Blues")
plt.title("Attention Heatmap")
plt.show()

"""________________________________________
📊 **Output**

*   Heatmap showing importance of each word
"""