# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KJarmTgnq67OOELWeq5_8X7TDjWOgP4

## Lab 7: BERT Fine-Tuning

### 🎯 Objective
To fine-tune BERT for text classification.

### ⚙️ Methodology
* Load pre-trained BERT
* Tokenize input
* Add classification layer
* Train on dataset

### 💻 Code Snippet
"""



"""### 📊 Output
* High accuracy classification model

### Alternative: BERT Fine-Tuning with TensorFlow Hub

Given the persistent issues with the `transformers` library, we will switch to using `tensorflow_hub` to achieve the same objective of fine-tuning BERT for text classification. This approach leverages pre-trained BERT models directly from TensorFlow Hub, integrating them seamlessly into a Keras model.
"""

!pip install tensorflow_text tensorflow_hub

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

# Define the BERT model to use (e.g., 'bert_en_uncased_L-12_H-768_A-12')
# For preprocessing, we need the corresponding preprocessor
bert_model_name = 'small_bert/bert_en_uncased_L-2_H-128_A-2' # Changed to small_bert for debugging

# Map model names to their Hub URLs
map_name_to_handle = {
    'bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3',
    'bert_en_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/3',
    'bert_multi_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/3',
    'small_bert/bert_en_uncased_L-2_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1',
    # You can add more BERT variants here as needed
}

map_model_to_preprocess = {
    'bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3',
    'bert_en_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_cased_preprocess/3',
    'bert_multi_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/3',
    'small_bert/bert_en_uncased_L-2_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3',
}

bert_handle = map_name_to_handle[bert_model_name]
bert_preprocess_handle = map_model_to_preprocess[bert_model_name]

print(f'BERT model selected: {bert_handle}')
print(f'Preprocess model selected: {bert_preprocess_handle}')

# Load the preprocessor and BERT encoder
bert_preprocess_model = hub.KerasLayer(bert_preprocess_handle)
bert_model = hub.KerasLayer(bert_handle)

# Example data
texts = tf.constant(["I love AI", "I hate bugs"])
labels = tf.constant([1, 0], dtype=tf.int32)

# Preprocess the texts
text_inputs = bert_preprocess_model(texts)
print("Preprocessed inputs:", text_inputs)

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

# Define the BERT model to use
bert_model_name = 'small_bert/bert_en_uncased_L-2_H-128_A-2'

# Map model names to their Hub URLs
map_name_to_handle = {
    'bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3',
    'bert_en_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/3',
    'bert_multi_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/3',
    'small_bert/bert_en_uncased_L-2_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1',
}

map_model_to_preprocess = {
    'bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3',
    'bert_en_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_cased_preprocess/3',
    'bert_multi_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/3',
    'small_bert/bert_en_uncased_L-2_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3',
}

bert_handle = map_name_to_handle[bert_model_name]
bert_preprocess_handle = map_model_to_preprocess[bert_model_name]

# Define custom Keras Layers to wrap the TensorFlow Hub layers
# This helps ensure correct symbolic tensor handling in some environments/versions
class TextPreprocessorLayer(tf.keras.layers.Layer):
  def __init__(self, preprocess_handle, **kwargs):
    super(TextPreprocessorLayer, self).__init__(**kwargs)
    self.preprocessor = hub.KerasLayer(preprocess_handle)

  def call(self, inputs):
    return self.preprocessor(inputs)

class BERTEncoderLayer(tf.keras.layers.Layer):
  def __init__(self, bert_handle, trainable=False, **kwargs):
    super(BERTEncoderLayer, self).__init__(**kwargs)
    self.encoder = hub.KerasLayer(bert_handle, trainable=trainable)

  def call(self, inputs):
    return self.encoder(inputs)

# Build a classification model
# Define a single input layer for raw text strings
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')

# Pass the raw text input through the custom BERT preprocessor layer
preprocessor_layer = TextPreprocessorLayer(bert_preprocess_handle, name='text_preprocessor_layer')
preprocessed_text_inputs = preprocessor_layer(text_input)

# Pass the preprocessed inputs to the custom BERT encoder layer
encoder_layer = BERTEncoderLayer(bert_handle, trainable=False, name='BERT_encoder_layer')
outputs = encoder_layer(preprocessed_text_inputs)

# Use the pooled output for classification
net = outputs['pooled_output']
net = tf.keras.layers.Dropout(0.1)(net)
output = tf.keras.layers.Dense(1, activation='sigmoid', name='classifier')(net)

# Create the Keras model, with the raw text input and the final output
model = tf.keras.Model(inputs=text_input, outputs=output)

# Print model summary
model.summary()

# Compile the model
loss = tf.keras.losses.BinaryCrossentropy(from_logits=False)
metrics = tf.metrics.BinaryAccuracy()

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=3e-5),
              loss=loss,
              metrics=[metrics])

# Example data for training (should be raw text as the model now handles preprocessing internally)
texts = tf.constant(["I love AI", "I hate bugs"])
labels = tf.constant([1, 0], dtype=tf.int32)

# Train the model
# Pass the raw text inputs and labels to the model
history = model.fit(
    x=texts,
    y=labels,
    epochs=2
)

print("Training complete!")

