# -*- coding: utf-8 -*-
"""lab 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mYvlGAQ4eoNkKngG0-DVuLj3nvvT0wA
"""

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

input_dim = 20
latent_dim = 2

inputs = Input(shape=(input_dim,))
encoded = Dense(10, activation='relu')(inputs)
latent = Dense(latent_dim)(encoded)

decoded = Dense(10, activation='relu')(latent)
outputs = Dense(input_dim, activation='sigmoid')(decoded)

vae = Model(inputs, outputs)
vae.compile(optimizer='adam', loss='mse')

"""### Variational Autoencoder (VAE) Code Explanation

This cell defines a simple Variational Autoencoder (VAE) using `tensorflow.keras`.

*   **`input_dim = 20`**: This sets the dimensionality of the input data. Each data point will have 20 features.
*   **`latent_dim = 2`**: This specifies the dimensionality of the latent space. The VAE will compress the 20-dimensional input into a 2-dimensional representation.

#### Encoder Part:
*   **`inputs = Input(shape=(input_dim,))`**: Defines the input layer, expecting vectors of `input_dim` (20) features.
*   **`encoded = Dense(10, activation='relu')(inputs)`**: This is the first hidden layer of the encoder. It reduces the input from 20 dimensions to 10 dimensions, using a ReLU activation function.
*   **`latent = Dense(latent_dim)(encoded)`**: This is the output layer of the encoder, producing the `latent_dim` (2) dimensional latent space representation.

#### Decoder Part:
*   **`decoded = Dense(10, activation='relu')(latent)`**: This is the first hidden layer of the decoder. It takes the `latent_dim` (2) representation and expands it to 10 dimensions, using a ReLU activation.
*   **`outputs = Dense(input_dim, activation='sigmoid')(decoded)`**: This is the output layer of the decoder. It reconstructs the original `input_dim` (20) features. A `sigmoid` activation is often used when the input data values are normalized between 0 and 1.

#### Model Compilation:
*   **`vae = Model(inputs, outputs)`**: Creates the VAE model, connecting the input layer to the final output layer through the encoder and decoder.
*   **`vae.compile(optimizer='adam', loss='mse')`**: Compiles the model for training:
    *   **`optimizer='adam'`**: Uses the Adam optimization algorithm to adjust model weights during training.
    *   **`loss='mse'`**: Uses Mean Squared Error (MSE) as the loss function, which measures the difference between the original input and the reconstructed output.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

generator = Sequential([
    Dense(16, activation='relu', input_dim=10),
    Dense(1, activation='sigmoid')
])

discriminator = Sequential([
    Dense(16, activation='relu', input_dim=1),
    Dense(1, activation='sigmoid')
])

"""### Generative Adversarial Network (GAN) Components Explanation

This cell defines the two main components of a simple Generative Adversarial Network (GAN): a Generator and a Discriminator, both using `tensorflow.keras.models.Sequential`.

#### Generator Model:
*   **`generator = Sequential([...])`**: Defines the Generator network as a sequential stack of layers.
    *   **`Dense(16, activation='relu', input_dim=10)`**: This is the first layer of the Generator. It takes an input of 10 dimensions (typically random noise, the 'latent vector' for the GAN) and maps it to 16 features using a ReLU activation.
    *   **`Dense(1, activation='sigmoid')`**: This is the output layer of the Generator. It produces a single output value, which could represent a generated data point (e.g., a single pixel value, or a compressed feature). The `sigmoid` activation scales the output to be between 0 and 1, which is common for generation tasks.

#### Discriminator Model:
*   **`discriminator = Sequential([...])`**: Defines the Discriminator network as a sequential stack of layers.
    *   **`Dense(16, activation='relu', input_dim=1)`**: This is the first layer of the Discriminator. It takes a single input value (which would be either a real data point or a generated data point from the Generator) and maps it to 16 features using a ReLU activation.
    *   **`Dense(1, activation='sigmoid')`**: This is the output layer of the Discriminator. It produces a single output value, interpreted as the probability that the input data is 'real'. A `sigmoid` activation is used here to output a probability between 0 and 1.
"""

import torch
import torch.nn as nn

class SimpleGCN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(10, 2)

    def forward(self, x, adj):
        x = torch.matmul(adj, x)
        x = self.fc(x)
        return x

"""### Graph Convolutional Network (GCN) Code Explanation

This cell defines a very basic Graph Convolutional Network (GCN) using `torch` (PyTorch) for graph-structured data.

*   **`import torch`** and **`import torch.nn as nn`**: Imports the necessary PyTorch libraries for building neural networks.

#### `SimpleGCN` Class:
*   **`class SimpleGCN(nn.Module):`**: Defines a new class `SimpleGCN` that inherits from `nn.Module`, which is the base class for all neural network modules in PyTorch.

*   **`def __init__(self):`**: The constructor for the GCN module.
    *   **`super().__init__()`**: Calls the constructor of the parent `nn.Module` class.
    *   **`self.fc = nn.Linear(10, 2)`**: Defines a simple fully connected (linear) layer. This layer will transform the node features. It expects an input feature dimension of 10 and will output 2 features. In a real GCN, this linear transformation would typically be applied *after* the graph convolution step.

*   **`def forward(self, x, adj):`**: Defines the forward pass of the GCN, which describes how input data `x` (node features) and `adj` (adjacency matrix) are processed through the network.
    *   **`x = torch.matmul(adj, x)`**: This is the core graph convolution step in this simplified model. It performs a matrix multiplication between the `adjacency matrix` (`adj`) and the `node features` (`x`).
        *   **`x`**: Represents the features of each node in the graph. If you have `N` nodes and `F` features per node, `x` would typically be an `N x F` tensor.
        *   **`adj`**: Represents the adjacency matrix of the graph, showing connections between nodes. If you have `N` nodes, `adj` would be an `N x N` tensor.
        *   The multiplication `adj @ x` effectively aggregates information from a node's neighbors. Each node's new feature representation becomes a sum of its neighbors' features (assuming `adj` is binary or normalized).
    *   **`x = self.fc(x)`**: After the graph convolution, the aggregated node features are passed through the fully connected layer defined in `__init__`. This applies a linear transformation to the features of each node.
    *   **`return x`**: The method returns the updated node features, which now incorporate information from their neighborhood.
"""

